import { describe, expect, it, vi } from "vitest";
import { createAzureDevOpsServices } from "../src/domain/index.js";

describe("service inventory", () => {
  it("exposes the full release-ready service surface", () => {
    const services = createAzureDevOpsServices(
      {
        get: vi.fn(),
        post: vi.fn(),
      },
      {
        azdoProjectAllowlist: [],
      },
    );

    expect(Object.keys(services).sort()).toEqual(
      [
        "analyzePipelineFailure",
        "analyzeTestFailureImpact",
        "clusterWorkItemsBySimilarity",
        "exportTestPlanFull",
        "exportTraceabilityDataset",
        "exportWorkItemsDelta",
        "exportWorkItemsFull",
        "findDuplicateCandidates",
        "findSimilarWorkItems",
        "getBlockedItems",
        "getCommitFull",
        "getCrossProjectDependencies",
        "getDashboardWidgetData",
        "getMyDailyDigest",
        "getPullRequestDiff",
        "getPullRequestFull",
        "getPullRequestWorkItems",
        "getRequirementTraceabilityReport",
        "getSprintCapacity",
        "getSprintSummary",
        "getTestPlan",
        "getTestPlanSuitesTree",
        "getTestPointHistory",
        "getTestRunFull",
        "getTestSuite",
        "getTraceabilityChain",
        "getUserStoryTestCoverage",
        "getWikiPage",
        "getWorkItem",
        "getWorkItemFull",
        "getWorkItemRelationsGraph",
        "listAreaPaths",
        "listIterationPaths",
        "listLinkedWorkItems",
        "listPipelineArtifacts",
        "listPipelineRuns",
        "listPipelines",
        "listProjects",
        "listPullRequestCommits",
        "listPullRequests",
        "listRepositories",
        "listSavedQueries",
        "listTags",
        "listTestCases",
        "listTestCasesFull",
        "listTestPlans",
        "listTestPoints",
        "listTestRuns",
        "listTestSuites",
        "listWorkItemCategories",
        "listWorkItemComments",
        "listWorkItemFields",
        "listWorkItemLinkTypes",
        "listWorkItemRevisions",
        "listWorkItemTestLinks",
        "listWorkItemTypes",
        "listWorkItemUpdates",
        "resolveIdentity",
        "runSavedQuery",
        "searchCommitsByWorkItem",
        "searchPullRequestsByWorkItem",
        "searchWorkItems",
        "searchWorkItemsAdvanced",
      ].sort(),
    );
  });
});
