import { describe, expect, it } from "vitest";
import {
  buildLinkedWorkItemsSummaryFromGraph,
  buildTraceabilityChainsFromGraph,
  normalizeRelationCategory,
  normalizeRelationDirection,
} from "../src/domain/traceability.js";

describe("traceability helpers", () => {
  it("normalizes relation categories and directions from Azure DevOps reference names", () => {
    expect(normalizeRelationCategory("System.LinkTypes.Dependency-Forward")).toBe(
      "dependency",
    );
    expect(normalizeRelationCategory("System.LinkTypes.Hierarchy-Reverse")).toBe(
      "hierarchy",
    );
    expect(normalizeRelationCategory("ArtifactLink", "resourceLink")).toBe("external");

    expect(normalizeRelationDirection("System.LinkTypes.Dependency-Forward", true)).toBe(
      "forward",
    );
    expect(normalizeRelationDirection("System.LinkTypes.Dependency-Reverse", true)).toBe(
      "reverse",
    );
    expect(normalizeRelationDirection("System.LinkTypes.Related", false)).toBe(
      "bidirectional",
    );
  });

  it("builds traceability chains without looping forever on cyclic graphs", () => {
    const chains = buildTraceabilityChainsFromGraph({
      rootId: 1,
      rootProject: "Allowed Project",
      maxDepth: 3,
      relationTypeFilter: [],
      nodes: [
        {
          id: 1,
          project: "Allowed Project",
          title: "Root",
          state: "Active",
          workItemType: "Bug",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 0,
          isRoot: true,
        },
        {
          id: 2,
          project: "Allowed Project",
          title: "Middle",
          state: "Active",
          workItemType: "Task",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 1,
          isRoot: false,
        },
        {
          id: 3,
          project: "Shared Project",
          title: "Leaf",
          state: "New",
          workItemType: "Test Case",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 2,
          isRoot: false,
        },
      ],
      edges: [
        {
          sourceId: 1,
          targetId: 2,
          sourceProject: "Allowed Project",
          targetProject: "Allowed Project",
          referenceName: "System.LinkTypes.Dependency-Forward",
          name: "Successor",
          oppositeReferenceName: "System.LinkTypes.Dependency-Reverse",
          topology: "dependency",
          category: "dependency",
          direction: "forward",
          isCrossProject: false,
          attributes: {},
        },
        {
          sourceId: 2,
          targetId: 1,
          sourceProject: "Allowed Project",
          targetProject: "Allowed Project",
          referenceName: "System.LinkTypes.Dependency-Reverse",
          name: "Predecessor",
          oppositeReferenceName: "System.LinkTypes.Dependency-Forward",
          topology: "dependency",
          category: "dependency",
          direction: "reverse",
          isCrossProject: false,
          attributes: {},
        },
        {
          sourceId: 2,
          targetId: 3,
          sourceProject: "Allowed Project",
          targetProject: "Shared Project",
          referenceName: "Microsoft.VSTS.Common.TestedBy-Forward",
          name: "Tested By",
          oppositeReferenceName: "Microsoft.VSTS.Common.TestedBy-Reverse",
          topology: "network",
          category: "test",
          direction: "forward",
          isCrossProject: true,
          attributes: {},
        },
      ],
      skippedRelations: [],
      relationTypesEncountered: [
        "Microsoft.VSTS.Common.TestedBy-Forward",
        "System.LinkTypes.Dependency-Forward",
        "System.LinkTypes.Dependency-Reverse",
      ],
      crossProjectNodeCount: 1,
      crossProjectEdgeCount: 1,
      traversal: {
        visitedNodeCount: 3,
        exploredEdgeCount: 3,
        skippedRelationCount: 0,
        truncatedAtDepth: false,
      },
    });

    expect(chains).toHaveLength(1);
    expect(chains[0]).toEqual({
      chainId: "1->2->3",
      nodeIds: [1, 2, 3],
      steps: [
        {
          fromId: 1,
          toId: 2,
          referenceName: "System.LinkTypes.Dependency-Forward",
          category: "dependency",
          direction: "forward",
        },
        {
          fromId: 2,
          toId: 3,
          referenceName: "Microsoft.VSTS.Common.TestedBy-Forward",
          category: "test",
          direction: "forward",
        },
      ],
      terminalNodeId: 3,
      terminalNodeProject: "Shared Project",
      terminalWorkItemType: "Test Case",
      containsCrossProjectItems: true,
      cycleDetected: true,
      endsAtMaxDepth: false,
    });
  });

  it("builds a flattened linked work item summary with incoming relations and multiple root paths", () => {
    const summary = buildLinkedWorkItemsSummaryFromGraph({
      rootId: 1,
      rootProject: "Allowed Project",
      maxDepth: 3,
      relationTypeFilter: [],
      nodes: [
        {
          id: 1,
          project: "Allowed Project",
          title: "Root",
          state: "Active",
          workItemType: "Bug",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 0,
          isRoot: true,
        },
        {
          id: 2,
          project: "Allowed Project",
          title: "Intermediate",
          state: "Active",
          workItemType: "Task",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 1,
          isRoot: false,
        },
        {
          id: 3,
          project: "Shared Project",
          title: "Regression test",
          state: "Design",
          workItemType: "Test Case",
          assignedTo: null,
          createdBy: null,
          changedBy: null,
          createdDate: null,
          changedDate: null,
          closedDate: null,
          areaPath: null,
          iterationPath: null,
          tags: null,
          reason: null,
          priority: null,
          severity: null,
          commentCount: null,
          activityDate: null,
          description: null,
          url: null,
          depth: 2,
          isRoot: false,
        },
      ],
      edges: [
        {
          sourceId: 1,
          targetId: 2,
          sourceProject: "Allowed Project",
          targetProject: "Allowed Project",
          referenceName: "System.LinkTypes.Dependency-Forward",
          name: "Successor",
          oppositeReferenceName: "System.LinkTypes.Dependency-Reverse",
          topology: "dependency",
          category: "dependency",
          direction: "forward",
          isCrossProject: false,
          attributes: {},
        },
        {
          sourceId: 1,
          targetId: 3,
          sourceProject: "Allowed Project",
          targetProject: "Shared Project",
          referenceName: "System.LinkTypes.Related",
          name: "Related",
          oppositeReferenceName: null,
          topology: "network",
          category: "related",
          direction: "bidirectional",
          isCrossProject: true,
          attributes: {},
        },
        {
          sourceId: 2,
          targetId: 3,
          sourceProject: "Allowed Project",
          targetProject: "Shared Project",
          referenceName: "Microsoft.VSTS.Common.TestedBy-Forward",
          name: "Tested By",
          oppositeReferenceName: "Microsoft.VSTS.Common.TestedBy-Reverse",
          topology: "network",
          category: "test",
          direction: "forward",
          isCrossProject: true,
          attributes: {},
        },
      ],
      skippedRelations: [],
      relationTypesEncountered: [
        "Microsoft.VSTS.Common.TestedBy-Forward",
        "System.LinkTypes.Dependency-Forward",
        "System.LinkTypes.Related",
      ],
      crossProjectNodeCount: 1,
      crossProjectEdgeCount: 2,
      traversal: {
        visitedNodeCount: 3,
        exploredEdgeCount: 3,
        skippedRelationCount: 0,
        truncatedAtDepth: false,
      },
    });

    expect(summary.root.id).toBe(1);
    expect(summary.totalLinkedWorkItems).toBe(2);
    expect(summary.linkedWorkItems.map((item) => item.id)).toEqual([2, 3]);
    expect(summary.linkedWorkItems[1]).toEqual(
      expect.objectContaining({
        id: 3,
        isCrossProject: true,
        pathCount: 2,
        relationTypes: [
          "Microsoft.VSTS.Common.TestedBy-Forward",
          "System.LinkTypes.Related",
        ],
        relationCategories: ["related", "test"],
      }),
    );
    expect(summary.linkedWorkItems[1]?.incomingRelations).toHaveLength(2);
    expect(summary.linkedWorkItems[1]?.pathsFromRoot.map((path) => path.nodeIds)).toEqual([
      [1, 2, 3],
      [1, 3],
    ]);
  });
});
